// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.5
// 	protoc        v5.29.3
// source: protos/common/common.proto

package common

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type QuestionType int32

const (
	QuestionType_SINGLE_CHOICE   QuestionType = 0 // Одиночный выбор (radio button)
	QuestionType_MULTIPLE_CHOICE QuestionType = 1 // Множественный выбор (checkboxes)
	QuestionType_OPEN_ENDED      QuestionType = 2 // Текстовый ответ
	QuestionType_NUMERIC_INPUT   QuestionType = 3 // Числовой ввод
)

// Enum value maps for QuestionType.
var (
	QuestionType_name = map[int32]string{
		0: "SINGLE_CHOICE",
		1: "MULTIPLE_CHOICE",
		2: "OPEN_ENDED",
		3: "NUMERIC_INPUT",
	}
	QuestionType_value = map[string]int32{
		"SINGLE_CHOICE":   0,
		"MULTIPLE_CHOICE": 1,
		"OPEN_ENDED":      2,
		"NUMERIC_INPUT":   3,
	}
)

func (x QuestionType) Enum() *QuestionType {
	p := new(QuestionType)
	*p = x
	return p
}

func (x QuestionType) String() string {
	return protoimpl.X.EnumStringOf(x.Descriptor(), protoreflect.EnumNumber(x))
}

func (QuestionType) Descriptor() protoreflect.EnumDescriptor {
	return file_protos_common_common_proto_enumTypes[0].Descriptor()
}

func (QuestionType) Type() protoreflect.EnumType {
	return &file_protos_common_common_proto_enumTypes[0]
}

func (x QuestionType) Number() protoreflect.EnumNumber {
	return protoreflect.EnumNumber(x)
}

// Deprecated: Use QuestionType.Descriptor instead.
func (QuestionType) EnumDescriptor() ([]byte, []int) {
	return file_protos_common_common_proto_rawDescGZIP(), []int{0}
}

type Question struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Text          string                 `protobuf:"bytes,2,opt,name=text,proto3" json:"text,omitempty"`
	QuestionType  QuestionType           `protobuf:"varint,3,opt,name=question_type,json=questionType,proto3,enum=protos.common.QuestionType" json:"question_type,omitempty"`
	Options       []string               `protobuf:"bytes,4,rep,name=options,proto3" json:"options,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Question) Reset() {
	*x = Question{}
	mi := &file_protos_common_common_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Question) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Question) ProtoMessage() {}

func (x *Question) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_common_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Question.ProtoReflect.Descriptor instead.
func (*Question) Descriptor() ([]byte, []int) {
	return file_protos_common_common_proto_rawDescGZIP(), []int{0}
}

func (x *Question) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *Question) GetText() string {
	if x != nil {
		return x.Text
	}
	return ""
}

func (x *Question) GetQuestionType() QuestionType {
	if x != nil {
		return x.QuestionType
	}
	return QuestionType_SINGLE_CHOICE
}

func (x *Question) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

type MutlipleChoiceAnswer struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	MultipleChoice []string               `protobuf:"bytes,3,rep,name=multiple_choice,json=multipleChoice,proto3" json:"multiple_choice,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *MutlipleChoiceAnswer) Reset() {
	*x = MutlipleChoiceAnswer{}
	mi := &file_protos_common_common_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MutlipleChoiceAnswer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MutlipleChoiceAnswer) ProtoMessage() {}

func (x *MutlipleChoiceAnswer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_common_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MutlipleChoiceAnswer.ProtoReflect.Descriptor instead.
func (*MutlipleChoiceAnswer) Descriptor() ([]byte, []int) {
	return file_protos_common_common_proto_rawDescGZIP(), []int{1}
}

func (x *MutlipleChoiceAnswer) GetMultipleChoice() []string {
	if x != nil {
		return x.MultipleChoice
	}
	return nil
}

type Answer struct {
	state protoimpl.MessageState `protogen:"open.v1"`
	// Types that are valid to be assigned to Answer:
	//
	//	*Answer_SingleChoice
	//	*Answer_MultipleChoice
	//	*Answer_OpenEnded
	//	*Answer_NumericInput
	Answer        isAnswer_Answer `protobuf_oneof:"answer"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *Answer) Reset() {
	*x = Answer{}
	mi := &file_protos_common_common_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *Answer) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*Answer) ProtoMessage() {}

func (x *Answer) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_common_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use Answer.ProtoReflect.Descriptor instead.
func (*Answer) Descriptor() ([]byte, []int) {
	return file_protos_common_common_proto_rawDescGZIP(), []int{2}
}

func (x *Answer) GetAnswer() isAnswer_Answer {
	if x != nil {
		return x.Answer
	}
	return nil
}

func (x *Answer) GetSingleChoice() string {
	if x != nil {
		if x, ok := x.Answer.(*Answer_SingleChoice); ok {
			return x.SingleChoice
		}
	}
	return ""
}

func (x *Answer) GetMultipleChoice() *MultipleChoice {
	if x != nil {
		if x, ok := x.Answer.(*Answer_MultipleChoice); ok {
			return x.MultipleChoice
		}
	}
	return nil
}

func (x *Answer) GetOpenEnded() string {
	if x != nil {
		if x, ok := x.Answer.(*Answer_OpenEnded); ok {
			return x.OpenEnded
		}
	}
	return ""
}

func (x *Answer) GetNumericInput() int32 {
	if x != nil {
		if x, ok := x.Answer.(*Answer_NumericInput); ok {
			return x.NumericInput
		}
	}
	return 0
}

type isAnswer_Answer interface {
	isAnswer_Answer()
}

type Answer_SingleChoice struct {
	SingleChoice string `protobuf:"bytes,1,opt,name=single_choice,json=singleChoice,proto3,oneof"` // Одиночный выбор
}

type Answer_MultipleChoice struct {
	MultipleChoice *MultipleChoice `protobuf:"bytes,2,opt,name=multiple_choice,json=multipleChoice,proto3,oneof"` // Множественный выбор (с массивом)
}

type Answer_OpenEnded struct {
	OpenEnded string `protobuf:"bytes,3,opt,name=open_ended,json=openEnded,proto3,oneof"` // Текстовый ответ
}

type Answer_NumericInput struct {
	NumericInput int32 `protobuf:"varint,4,opt,name=numeric_input,json=numericInput,proto3,oneof"` // Числовой ввод
}

func (*Answer_SingleChoice) isAnswer_Answer() {}

func (*Answer_MultipleChoice) isAnswer_Answer() {}

func (*Answer_OpenEnded) isAnswer_Answer() {}

func (*Answer_NumericInput) isAnswer_Answer() {}

type MultipleChoice struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Options       []string               `protobuf:"bytes,1,rep,name=options,proto3" json:"options,omitempty"` // Массив для множественного выбора
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *MultipleChoice) Reset() {
	*x = MultipleChoice{}
	mi := &file_protos_common_common_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *MultipleChoice) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*MultipleChoice) ProtoMessage() {}

func (x *MultipleChoice) ProtoReflect() protoreflect.Message {
	mi := &file_protos_common_common_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use MultipleChoice.ProtoReflect.Descriptor instead.
func (*MultipleChoice) Descriptor() ([]byte, []int) {
	return file_protos_common_common_proto_rawDescGZIP(), []int{3}
}

func (x *MultipleChoice) GetOptions() []string {
	if x != nil {
		return x.Options
	}
	return nil
}

var File_protos_common_common_proto protoreflect.FileDescriptor

var file_protos_common_common_proto_rawDesc = string([]byte{
	0x0a, 0x1a, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2f,
	0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x12, 0x0d, 0x70, 0x72,
	0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x22, 0x8a, 0x01, 0x0a, 0x08,
	0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x12, 0x0e, 0x0a, 0x02, 0x69, 0x64, 0x18, 0x01,
	0x20, 0x01, 0x28, 0x09, 0x52, 0x02, 0x69, 0x64, 0x12, 0x12, 0x0a, 0x04, 0x74, 0x65, 0x78, 0x74,
	0x18, 0x02, 0x20, 0x01, 0x28, 0x09, 0x52, 0x04, 0x74, 0x65, 0x78, 0x74, 0x12, 0x40, 0x0a, 0x0d,
	0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x5f, 0x74, 0x79, 0x70, 0x65, 0x18, 0x03, 0x20,
	0x01, 0x28, 0x0e, 0x32, 0x1b, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f, 0x6d,
	0x6d, 0x6f, 0x6e, 0x2e, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65,
	0x52, 0x0c, 0x71, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54, 0x79, 0x70, 0x65, 0x12, 0x18,
	0x0a, 0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x18, 0x04, 0x20, 0x03, 0x28, 0x09, 0x52,
	0x07, 0x6f, 0x70, 0x74, 0x69, 0x6f, 0x6e, 0x73, 0x22, 0x3f, 0x0a, 0x14, 0x4d, 0x75, 0x74, 0x6c,
	0x69, 0x70, 0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x41, 0x6e, 0x73, 0x77, 0x65, 0x72,
	0x12, 0x27, 0x0a, 0x0f, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x6f,
	0x69, 0x63, 0x65, 0x18, 0x03, 0x20, 0x03, 0x28, 0x09, 0x52, 0x0e, 0x6d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x22, 0xcb, 0x01, 0x0a, 0x06, 0x41, 0x6e,
	0x73, 0x77, 0x65, 0x72, 0x12, 0x25, 0x0a, 0x0d, 0x73, 0x69, 0x6e, 0x67, 0x6c, 0x65, 0x5f, 0x63,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x01, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x0c, 0x73,
	0x69, 0x6e, 0x67, 0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x48, 0x0a, 0x0f, 0x6d,
	0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x5f, 0x63, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x18, 0x02,
	0x20, 0x01, 0x28, 0x0b, 0x32, 0x1d, 0x2e, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2e, 0x63, 0x6f,
	0x6d, 0x6d, 0x6f, 0x6e, 0x2e, 0x4d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x43, 0x68, 0x6f,
	0x69, 0x63, 0x65, 0x48, 0x00, 0x52, 0x0e, 0x6d, 0x75, 0x6c, 0x74, 0x69, 0x70, 0x6c, 0x65, 0x43,
	0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x1f, 0x0a, 0x0a, 0x6f, 0x70, 0x65, 0x6e, 0x5f, 0x65, 0x6e,
	0x64, 0x65, 0x64, 0x18, 0x03, 0x20, 0x01, 0x28, 0x09, 0x48, 0x00, 0x52, 0x09, 0x6f, 0x70, 0x65,
	0x6e, 0x45, 0x6e, 0x64, 0x65, 0x64, 0x12, 0x25, 0x0a, 0x0d, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69,
	0x63, 0x5f, 0x69, 0x6e, 0x70, 0x75, 0x74, 0x18, 0x04, 0x20, 0x01, 0x28, 0x05, 0x48, 0x00, 0x52,
	0x0c, 0x6e, 0x75, 0x6d, 0x65, 0x72, 0x69, 0x63, 0x49, 0x6e, 0x70, 0x75, 0x74, 0x42, 0x08, 0x0a,
	0x06, 0x61, 0x6e, 0x73, 0x77, 0x65, 0x72, 0x22, 0x2a, 0x0a, 0x0e, 0x4d, 0x75, 0x6c, 0x74, 0x69,
	0x70, 0x6c, 0x65, 0x43, 0x68, 0x6f, 0x69, 0x63, 0x65, 0x12, 0x18, 0x0a, 0x07, 0x6f, 0x70, 0x74,
	0x69, 0x6f, 0x6e, 0x73, 0x18, 0x01, 0x20, 0x03, 0x28, 0x09, 0x52, 0x07, 0x6f, 0x70, 0x74, 0x69,
	0x6f, 0x6e, 0x73, 0x2a, 0x59, 0x0a, 0x0c, 0x51, 0x75, 0x65, 0x73, 0x74, 0x69, 0x6f, 0x6e, 0x54,
	0x79, 0x70, 0x65, 0x12, 0x11, 0x0a, 0x0d, 0x53, 0x49, 0x4e, 0x47, 0x4c, 0x45, 0x5f, 0x43, 0x48,
	0x4f, 0x49, 0x43, 0x45, 0x10, 0x00, 0x12, 0x13, 0x0a, 0x0f, 0x4d, 0x55, 0x4c, 0x54, 0x49, 0x50,
	0x4c, 0x45, 0x5f, 0x43, 0x48, 0x4f, 0x49, 0x43, 0x45, 0x10, 0x01, 0x12, 0x0e, 0x0a, 0x0a, 0x4f,
	0x50, 0x45, 0x4e, 0x5f, 0x45, 0x4e, 0x44, 0x45, 0x44, 0x10, 0x02, 0x12, 0x11, 0x0a, 0x0d, 0x4e,
	0x55, 0x4d, 0x45, 0x52, 0x49, 0x43, 0x5f, 0x49, 0x4e, 0x50, 0x55, 0x54, 0x10, 0x03, 0x42, 0x0f,
	0x5a, 0x0d, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x73, 0x2f, 0x63, 0x6f, 0x6d, 0x6d, 0x6f, 0x6e, 0x62,
	0x06, 0x70, 0x72, 0x6f, 0x74, 0x6f, 0x33,
})

var (
	file_protos_common_common_proto_rawDescOnce sync.Once
	file_protos_common_common_proto_rawDescData []byte
)

func file_protos_common_common_proto_rawDescGZIP() []byte {
	file_protos_common_common_proto_rawDescOnce.Do(func() {
		file_protos_common_common_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_protos_common_common_proto_rawDesc), len(file_protos_common_common_proto_rawDesc)))
	})
	return file_protos_common_common_proto_rawDescData
}

var file_protos_common_common_proto_enumTypes = make([]protoimpl.EnumInfo, 1)
var file_protos_common_common_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_protos_common_common_proto_goTypes = []any{
	(QuestionType)(0),            // 0: protos.common.QuestionType
	(*Question)(nil),             // 1: protos.common.Question
	(*MutlipleChoiceAnswer)(nil), // 2: protos.common.MutlipleChoiceAnswer
	(*Answer)(nil),               // 3: protos.common.Answer
	(*MultipleChoice)(nil),       // 4: protos.common.MultipleChoice
}
var file_protos_common_common_proto_depIdxs = []int32{
	0, // 0: protos.common.Question.question_type:type_name -> protos.common.QuestionType
	4, // 1: protos.common.Answer.multiple_choice:type_name -> protos.common.MultipleChoice
	2, // [2:2] is the sub-list for method output_type
	2, // [2:2] is the sub-list for method input_type
	2, // [2:2] is the sub-list for extension type_name
	2, // [2:2] is the sub-list for extension extendee
	0, // [0:2] is the sub-list for field type_name
}

func init() { file_protos_common_common_proto_init() }
func file_protos_common_common_proto_init() {
	if File_protos_common_common_proto != nil {
		return
	}
	file_protos_common_common_proto_msgTypes[2].OneofWrappers = []any{
		(*Answer_SingleChoice)(nil),
		(*Answer_MultipleChoice)(nil),
		(*Answer_OpenEnded)(nil),
		(*Answer_NumericInput)(nil),
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_protos_common_common_proto_rawDesc), len(file_protos_common_common_proto_rawDesc)),
			NumEnums:      1,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   0,
		},
		GoTypes:           file_protos_common_common_proto_goTypes,
		DependencyIndexes: file_protos_common_common_proto_depIdxs,
		EnumInfos:         file_protos_common_common_proto_enumTypes,
		MessageInfos:      file_protos_common_common_proto_msgTypes,
	}.Build()
	File_protos_common_common_proto = out.File
	file_protos_common_common_proto_goTypes = nil
	file_protos_common_common_proto_depIdxs = nil
}
